export const WORKOUTS = {
  A: [
    {name:"Squat",resistance:"20 lb",sets:3,reps:"10",target:"Legs and glutes",setup:"Stand securely on the bands with feet around hip-width apart. Hold the bar at shoulder height.",movement:"Sit your hips back and down, keep your chest lifted, then press through the whole foot to stand.",avoid:"Knees collapsing inward, heels lifting or rushing."},
    {name:"Bent-over row",resistance:"20–30 lb",sets:3,reps:"10",target:"Upper back and arms",setup:"Stand on the bands and hinge forward from the hips with a long spine.",movement:"Pull the bar towards your lower ribs, pause, then lower slowly.",avoid:"Rounding your back, shrugging or jerking."},
    {name:"Chest press",resistance:"20 lb",sets:3,reps:"12",target:"Chest, shoulders and triceps",setup:"Secure the door anchor behind you at chest height and face away.",movement:"Press your hands forwards until your arms are almost straight, then return slowly.",avoid:"Arching your lower back or locking your elbows."},
    {name:"Romanian deadlift",resistance:"30 lb",sets:3,reps:"10",target:"Glutes and hamstrings",setup:"Stand on the bands with the bar in front of your thighs and knees softly bent.",movement:"Push your hips backwards while keeping the bar close to your legs. Stand by squeezing your glutes.",avoid:"Turning it into a squat or rounding your back."},
    {name:"Shoulder press",resistance:"20 lb",sets:3,reps:"10",target:"Shoulders and triceps",setup:"Stand on the bands and hold the bar at shoulder height.",movement:"Brace your middle and press overhead. Lower smoothly.",avoid:"Leaning backwards or shrugging."},
    {name:"Pallof press",resistance:"20 lb",sets:3,reps:"10 each side",target:"Core stability",setup:"Anchor the band at chest height and stand side-on.",movement:"Press straight out while resisting rotation, then return slowly.",avoid:"Twisting towards the anchor or holding your breath."}
  ],
  B: [
    {name:"Supported reverse lunge",resistance:"Bodyweight first",sets:3,reps:"8 each side",target:"Legs, glutes and balance",setup:"Stand beside a stable chair or wall.",movement:"Step one foot backwards and lower only as far as comfortable. Push through the front foot to return.",avoid:"A narrow step or the front knee collapsing inward."},
    {name:"Standing row",resistance:"20–30 lb",sets:3,reps:"12",target:"Upper back",setup:"Anchor at chest height and face it with your arms extended.",movement:"Draw your elbows back and squeeze your shoulder blades. Return with control.",avoid:"Shrugging, leaning backwards or flaring your ribs."},
    {name:"Biceps curl",resistance:"20 lb",sets:3,reps:"12",target:"Front of upper arms",setup:"Stand on the bands with arms by your sides and palms forwards.",movement:"Keep elbows tucked and curl your hands towards your shoulders.",avoid:"Swinging or moving your elbows forwards."},
    {name:"Triceps pressdown",resistance:"20 lb",sets:3,reps:"12",target:"Back of upper arms",setup:"Anchor overhead and keep your elbows tucked.",movement:"Straighten your arms towards the floor, then return slowly.",avoid:"Moving your upper arms or hunching your shoulders."},
    {name:"Glute kickback",resistance:"20 lb",sets:3,reps:"12 each side",target:"Glutes",setup:"Attach the ankle strap and hold something stable.",movement:"Move one leg backwards without rotating your hips. Return slowly.",avoid:"Arching your back or swinging your leg."},
    {name:"Standing wood chop",resistance:"20 lb",sets:3,reps:"10 each side",target:"Core and hips",setup:"Anchor at shoulder height and stand side-on with both hands on the handle.",movement:"Move diagonally across your body while your hips and upper body turn together.",avoid:"Pulling only with your arms or rushing."}
  ],
  C: [
    {name:"Deadlift",resistance:"30 lb",sets:3,reps:"10",target:"Glutes, hamstrings and back",setup:"Stand securely on the bands with the bar in front of your thighs.",movement:"Hinge from your hips, then drive through your feet to stand tall.",avoid:"Rounding your spine or pulling with your arms."},
    {name:"Chest fly",resistance:"20 lb",sets:3,reps:"12",target:"Chest and shoulders",setup:"Anchor behind you at chest height with arms open and elbows softly bent.",movement:"Bring your hands together in a wide arc, then reopen with control.",avoid:"Locking your elbows or overstretching behind you."},
    {name:"Lateral raise",resistance:"20 lb",sets:3,reps:"12",target:"Side shoulders",setup:"Stand on the bands with arms resting by your sides.",movement:"Raise your arms to around shoulder height and lower slowly.",avoid:"Shrugging or lifting above shoulder height."},
    {name:"Face pull",resistance:"20 lb",sets:3,reps:"12",target:"Upper back and rear shoulders",setup:"Anchor at face height and hold the handles with arms extended.",movement:"Pull towards eyebrow level with elbows wide.",avoid:"Leaning backwards or dropping your elbows."},
    {name:"Suitcase hold and march",resistance:"20–30 lb",sets:3,reps:"30–45 sec each side",target:"Core and posture",setup:"Hold resistance on one side and stand tall.",movement:"March slowly without leaning. Switch sides.",avoid:"Rushing, slumping or holding your breath."},
    {name:"Plank",resistance:"No band",sets:3,reps:"20–30 sec",target:"Core and shoulders",setup:"Use a wall, worktop, knees or toes.",movement:"Hold a straight line while breathing normally.",avoid:"Dropping or lifting your hips too far."}
  ]
};
